const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const source=fs.readFileSync(path.join(__dirname,'../../src/views/examSimulator.vue'),'utf8').match(/<script setup[^>]*>([\s\S]*?)<\/script>/)[1];
const ast=ts.createSourceFile('exam.ts',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS);
// Execute the production functions, with fixture data only at the spell-input boundary.
const declarations=ast.statements.filter(n=>ts.isFunctionDeclaration(n)&&!n.getText(ast).includes('import.meta')||ts.isVariableStatement(n)&&n.declarationList.declarations.some(d=>['stateArrayOwnershipBits','curseRatePowerScale'].includes(d.name.getText(ast)))).map(n=>n.getText(ast)).join('\n');
const js=ts.transpileModule(declarations,{compilerOptions:{target:ts.ScriptTarget.ES2020}}).outputText;
const keys=['playerAttackDowns','playerDamageDowns','playerEvasions','enemyDamageReductions','enemyDamageNulls','enemyEvasions','enemyCriticals','enemyAttackDowns','enemyDamageDowns','enemyDamageTakenUps','enemyCurses','enemyBlinds','enemyFreezes','playerBlinds','playerCurses','playerFreezes','burns','playerDamageTakenDowns','playerDamageTakenUps','playerContinueHeals','playerImmunities','playerGuts','playerBuffs','enemyAttackUps','enemyDamageUps','enemyGuts','enemyContinueHeals'];
function fixture(kind='ATTACK'){
 const c={exam:{value:{kind,difficulty:1}},simulationRuntimeCache:null,enemySlots:{value:[{id:'e1'},{id:'e2'}]},formatNumber:n=>Number(n).toLocaleString('en-US')};vm.createContext(c);vm.runInContext(js,c);c.getAutomaticOpponentDebuffs=()=>[{magicOption:'M1',buffOption:'呪い',powerOption:'極大',durationTurns:2,targetType:'opponent'}];
 const state=Object.fromEntries(keys.map(k=>[k,[]])),stats={playerDamage:20000,enemyMaxHp:100000,playerRemainHp:90000,playerTotalHp:100000,playerHeal:0,enemyDamage:0,finishTurn:5,scoreBuff:0,healBlock:0,advantage:0,equal:4,disadvantage:0,duo:0,advantageCombo:0,equalCombo:0,disadvantageCombo:0,advantageSingle:0,equalSingle:4,disadvantageSingle:0,advantageDamaged:0,disadvantageDamaged:0,evasion:0,debuff:0,specialChallengeScore:0,specialChallengeLabels:[]};
 const action={slotKey:'e1',effectKind:'heal',effectTarget:'自',effectValue:1000,duration:3};
 return {c,state,stats,action,curse:(roll=0)=>c.activatePlayerOpponentDebuffs('0-M1',action,undefined,state,()=>roll,stats,1,'test'),heal:(partial={},hp=90000)=>c.applyEnemySelfEffects({...action,...partial},state,hp,100000,stats),tick:(hp=90000)=>c.applyEnemyContinueHeal(state,hp,100000,stats)};
}
test('successful curse alone does not award ATTACK heal-block points',()=>{const f=fixture(),base=f.c.calculateScore(f.stats);f.curse();assert.equal(f.state.enemyCurses.length,1);assert.equal(f.stats.healBlock,0);assert.equal(f.c.calculateScore(f.stats),base);});
test('actual instant healing prevented awards exactly 180 before difficulty multiplier; log agrees',()=>{const f=fixture(),base=f.c.calculateScore(f.stats);f.curse();assert.equal(f.heal(),0);assert.equal(f.stats.healBlock,1);f.stats.score=f.c.calculateScore(f.stats);assert.equal(f.stats.score-base,180);f.stats.log=[];f.c.pushScoreBreakdownLog(f.stats);assert.match(f.stats.log.join('\n'),/回復阻害 \+180\(1回\)/);f.c.exam.value.difficulty=1.5;assert.equal(f.c.calculateScore(f.stats)-f.c.calculateScore({...f.stats,healBlock:0}),270);});
test('failed curse, other target, removal, and expiration do not count when no earlier heal was blocked',()=>{for(const mode of ['failure','other','removal','expiration']){const f=fixture();f.c.getAutomaticOpponentDebuffs=()=>[{buffOption:'呪い',powerOption:'中',durationTurns:2,targetType:'opponent'}];f.curse(mode==='failure'?.99:0);if(mode==='removal')f.c.removeEnemyNegativeEffects(f.state,['e1']);if(mode==='expiration'){f.c.tickTimedEffects(f.state);f.c.tickTimedEffects(f.state);}assert.equal(f.heal(mode==='other'?{slotKey:'e2'}:{}),1000,mode);assert.equal(f.stats.healBlock,0,mode);}});
test('zero-valued instant and continuous effects do not count',()=>{const f=fixture();f.curse();assert.equal(f.heal({effectValue:0}),0);f.heal({effectKind:'continueHeal',effectValue:0});f.state.enemyContinueHeals=[{targetEnemySlotKey:'e1',amount:0,turns:3}];assert.equal(f.tick(),0);assert.equal(f.stats.healBlock,0);});
test('full HP still counts a positive recovery effect explicitly blocked by curse (event semantics)',()=>{const f=fixture();f.curse();assert.equal(f.heal({},100000),0);assert.equal(f.stats.healBlock,1);const g=fixture();g.curse();g.state.enemyContinueHeals=[{targetEnemySlotKey:'e1',amount:1000,turns:3}];assert.equal(g.tick(100000),0);assert.equal(g.stats.healBlock,1);});
test('existing continuous heal counts only when an active healing tick is blocked; resumes after curse expiration',()=>{const f=fixture();f.heal({effectKind:'continueHeal',duration:5});f.curse();assert.equal(f.stats.healBlock,0);assert.equal(f.tick(),0);assert.equal(f.stats.healBlock,1);f.c.tickTimedEffects(f.state);f.c.tickTimedEffects(f.state);assert.equal(f.tick(),1000);assert.equal(f.stats.healBlock,1);});
test('new continuous effect blocked at application counts; expired or wrong-target tick does not',()=>{const f=fixture();f.curse();f.heal({effectKind:'continueHeal'});assert.equal(f.state.enemyContinueHeals.length,0);assert.equal(f.stats.healBlock,1);for(const entry of [{targetEnemySlotKey:'e2',amount:1000,turns:3},{targetEnemySlotKey:'e1',amount:1000,turns:0}]){const g=fixture();g.curse();g.state.enemyContinueHeals=[entry];g.tick();assert.equal(g.stats.healBlock,0);}});
test('multiple curses and blocked instant/continuous effects count once for the entire battle',()=>{const f=fixture();f.curse();f.curse();f.heal();f.heal();f.heal({effectKind:'continueHeal'});f.state.enemyContinueHeals=[{targetEnemySlotKey:'e1',amount:1000,turns:3}];f.tick();assert.equal(f.stats.healBlock,1);});
test('untargeted/global curse also prevents an untargeted continuing-heal event',()=>{const f=fixture();f.state.enemyCurses=[{rate:100,turns:2}];f.state.enemyContinueHeals=[{amount:1000,turns:3}];assert.equal(f.tick(),0);assert.equal(f.stats.healBlock,1);});
test('DEFENCE and BASIC retain healing prevention but no ATTACK counter or score bonus',()=>{for(const kind of ['DEFENCE','BASIC']){const f=fixture(kind),base=f.c.calculateScore(f.stats);f.curse();assert.equal(f.heal(),0);f.heal({effectKind:'continueHeal'});f.state.enemyContinueHeals=[{targetEnemySlotKey:'e1',amount:1000,turns:3}];assert.equal(f.tick(),0);assert.equal(f.stats.healBlock,0);assert.equal(f.c.calculateScore(f.stats),base);}});
test('forecast copies used by shared search evaluation never mutate original battle statistics',()=>{const f=fixture();f.curse();const copied=f.c.cloneSimulationStats(f.stats,false);f.c.applyEnemySelfEffects(f.action,f.state,90000,100000,copied);assert.equal(copied.healBlock,1);assert.equal(f.stats.healBlock,0);});
